# Generated by Django 5.2.17 on 2026-10-09 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('bio', models.TextField(blank=True, verbose_name='biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.TextField(help_text='Entradilla que se muestra en el listado.', verbose_name='resumen')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articulos/', verbose_name='imagen destacada')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.author', verbose_name='autor')),
                ('categories', models.ManyToManyField(related_name='articles', to='news.category', verbose_name='categorías')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-published_at'],
            },
        ),
    ]
