# Generated by Django 5.2.17 on 2026-10-02 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'género',
                'verbose_name_plural': 'géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('pais', models.CharField(blank=True, max_length=60, verbose_name='país')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personas/', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('duracion', models.PositiveIntegerField(blank=True, null=True, verbose_name='duración (minutos)')),
                ('sinopsis', models.TextField(blank=True, verbose_name='sinopsis')),
                ('cartel', models.ImageField(blank=True, null=True, upload_to='carteles/', verbose_name='cartel')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('generos', models.ManyToManyField(blank=True, related_name='peliculas', to='movies.genre', verbose_name='géneros')),
                ('directores', models.ManyToManyField(blank=True, related_name='peliculas_dirigidas', to='movies.person', verbose_name='directores')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'ordering': ['-anio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critico', models.CharField(max_length=100, verbose_name='crítico')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación (1-10)')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='movies.movie', verbose_name='película')),
            ],
            options={
                'verbose_name': 'valoración',
                'verbose_name_plural': 'valoraciones',
                'ordering': ['-puntuacion', 'fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('pelicula', 'critico'), name='unique_valoracion_por_critico')],
            },
        ),
    ]
